language: ruby

rvm:
  - 2.2

env:
  - RAILS_VERSION=master

sudo: false

bundler_args: "--binstubs --without documentation --path ../bundle --retry=3 --jobs=3"

before_install: "script/clone_all_rspec_repos"

before_script:
  # Rails 4.x complains with a bundler rails binstub in PROJECT_ROOT/bin/
  - rm -f bin/rails
  - bundle exec rails --version

script: "script/run_build 2>&1"

matrix:
  fast_finish: true
